version: '3.8'

services:
  api:
    build: .
    container_name: book-review-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run setup-db && npm start"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: bookreview-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
